package com.homektv.musicsource;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.homektv.domain.Song;
import com.homektv.repo.SongRepository;
import com.homektv.ws.ProgressBroadcaster;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;

class MusicMetadataScrapeServiceTest {
    private JdbcTemplate jdbc;
    private TransactionTemplate transactions;
    private SongRepository songRepository;
    private MusicSourceConfigService configService;
    private MusicMetadataScrapeWorker worker;
    private MusicMetadataApplyService applyService;
    private MusicMetadataScrapeService service;

    @BeforeEach
    void setUp() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:scrape-" + System.nanoTime() + ";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1");
        jdbc = new JdbcTemplate(dataSource);
        transactions = new TransactionTemplate(new DataSourceTransactionManager(dataSource));
        jdbc.execute("CREATE TABLE song_files(song_id BIGINT NOT NULL, valid BOOLEAN NOT NULL)");
        jdbc.execute("""
                CREATE TABLE music_metadata_scrape_batches(
                  id VARCHAR(36) PRIMARY KEY, mode VARCHAR(16) NOT NULL, status VARCHAR(16) NOT NULL,
                  auto_apply_threshold DOUBLE PRECISION NOT NULL, skipped_existing INTEGER NOT NULL DEFAULT 0,
                  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                  started_at TIMESTAMP WITH TIME ZONE, finished_at TIMESTAMP WITH TIME ZONE,
                  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)
                """);
        jdbc.execute("""
                CREATE TABLE song_external_matches(
                  song_id BIGINT NOT NULL, provider VARCHAR(24) NOT NULL, external_id VARCHAR(160) NOT NULL,
                  status VARCHAR(24) NOT NULL)
                """);
        jdbc.execute("""
                CREATE TABLE music_metadata_scrape_items(
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, batch_id VARCHAR(36) NOT NULL,
                  song_id BIGINT, original_title VARCHAR(500) NOT NULL, original_artist VARCHAR(500) NOT NULL,
                  status VARCHAR(24) NOT NULL, provider VARCHAR(24), external_id VARCHAR(160),
                  match_score DOUBLE PRECISION, result_json JSON, error_message VARCHAR(1000),
                  started_at TIMESTAMP WITH TIME ZONE, finished_at TIMESTAMP WITH TIME ZONE,
                  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)
                """);
        songRepository = mock(SongRepository.class);
        configService = mock(MusicSourceConfigService.class);
        worker = mock(MusicMetadataScrapeWorker.class);
        applyService = mock(MusicMetadataApplyService.class);
        when(configService.getConfig()).thenReturn(new MusicSourceConfig(
                true, Set.of(MusicProvider.QQ), 20, 5, 6, 1, 1500, 0.95));
        when(songRepository.findAllById(any())).thenAnswer(invocation -> {
            List<Song> songs = new ArrayList<>();
            for (Long id : (Iterable<Long>) invocation.getArgument(0)) songs.add(song(id));
            return songs;
        });
        service = new MusicMetadataScrapeService(jdbc, songRepository, configService, worker,
                applyService, new ObjectMapper(), mock(ProgressBroadcaster.class));
    }

    @Test
    void createsAllTaskFromValidKtvFilesAndDispatchesOnlyAfterCommit() {
        jdbc.batchUpdate("INSERT INTO song_files(song_id,valid) VALUES (?,?)",
                List.of(new Object[]{1L, true}, new Object[]{2L, false}, new Object[]{3L, true}));

        Map<String, Object> created = transactions.execute(status -> {
            Map<String, Object> result = service.start(true, List.of(), 0.91);
            verifyNoInteractions(worker);
            return result;
        });

        assertThat(created).containsEntry("mode", "ALL")
                .containsEntry("status", "RUNNING")
                .containsEntry("total", 2L)
                .containsEntry("pending", 2L)
                .containsEntry("autoApplyThreshold", 0.91);
        verify(worker).process((String) created.get("batchId"));
        assertThat(jdbc.queryForList("SELECT song_id FROM music_metadata_scrape_items ORDER BY song_id", Long.class))
                .containsExactly(1L, 3L);
    }

    @Test
    void createsSingleTaskWithoutWaitingForAFullLibraryRun() {
        Map<String, Object> created = transactions.execute(status -> service.start(false, List.of(8L), null));

        assertThat(created).containsEntry("mode", "SINGLE")
                .containsEntry("total", 1L)
                .containsEntry("autoApplyThreshold", 0.95);
        assertThat(jdbc.queryForObject("SELECT original_title FROM music_metadata_scrape_items", String.class))
                .isEqualTo("歌曲 8");
    }

    @Test
    void manuallyCompletesAnItemWithoutAnExternalCandidate() {
        Map<String, Object> created = transactions.execute(status -> service.start(false, List.of(9L), null));
        String batchId = (String) created.get("batchId");
        long itemId = jdbc.queryForObject("SELECT id FROM music_metadata_scrape_items WHERE batch_id=?", Long.class, batchId);
        jdbc.update("UPDATE music_metadata_scrape_items SET status='FAILED' WHERE id=?", itemId);

        service.applyItem(batchId, itemId, Set.of("album"), Map.of("album", "人工专辑"), null, null, false);

        verify(applyService).applyManual(eq(9L), any(MusicMetadataApplyService.ApplyRequest.class));
        assertThat(jdbc.queryForObject("SELECT status FROM music_metadata_scrape_items WHERE id=?", String.class, itemId))
                .isEqualTo("MANUAL_APPLIED");
    }

    @Test
    void skipsPreviouslyScrapedSongsInBatchRuns() {
        jdbc.batchUpdate("INSERT INTO song_files(song_id,valid) VALUES (?,?)",
                List.of(new Object[]{1L, true}, new Object[]{2L, true}, new Object[]{3L, true}));
        Map<String, Object> previous = transactions.execute(status -> service.start(false, List.of(1L), null));
        jdbc.update("UPDATE music_metadata_scrape_items SET status='REVIEW' WHERE batch_id=?", previous.get("batchId"));
        jdbc.update("UPDATE music_metadata_scrape_batches SET status='COMPLETED' WHERE id=?", previous.get("batchId"));
        jdbc.update("INSERT INTO song_external_matches(song_id,provider,external_id,status) VALUES (2,'QQ','track-2','APPLIED')");

        Map<String, Object> created = transactions.execute(status -> service.start(true, List.of(), null));

        assertThat(created).containsEntry("total", 1L).containsEntry("skippedExisting", 2);
        assertThat(jdbc.queryForList("SELECT song_id FROM music_metadata_scrape_items WHERE batch_id=?", Long.class, created.get("batchId")))
                .containsExactly(3L);
    }

    private static Song song(long id) {
        Song song = new Song();
        song.setId(id);
        song.setTitle("歌曲 " + id);
        song.setArtist("歌手 " + id);
        return song;
    }
}
